import type { Metadata } from "next";
import { Pangolin } from "next/font/google";
import "./globals.scss";
import Link from "next/link";

const pangolin = Pangolin({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-pangolin",
});

export const metadata: Metadata = {
  title: "Funlingo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pangolin.className} ${pangolin.variable}`}>
        <div className="header">
          <Link href="/">
            <img className="logo" src="/logo.png" />
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
